baseURL = "http://example.org/"
languageCode = "en-us"
title = "tex"
theme = "yourfolio"


[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"